package Enum;
/**
 * 
 * @author Kartik
 *
 */
public enum Enum_data
{ 
	WELCOMEPAGE,LOGINPAGE,URL,E,P,E1,EXCEL_PATH,BROWSER,PHOTOSHEET,ACTCOLOUMN,PHOTODESCRIPTION,PHOTOPATH,PROFILESHEET,
	ACTUSERNAME,PROPETRTYFILEPATH,PAGETYPE,ELEMENTTYPE,TCTYPE,LPTITLE,HPTITLE,WPTITLE,HOMEPAGE,ACTEDITPROFILEURL,ACTPROFILEURL,EPPAGE,PPAGE
	,ELEMENTNAME,EXTENTREPORTTPATH,EXTENTREPORTTITLE,EXTENTREPORTNAME,OVERRIDEREPORT
		
	,LOGINSHEET,LOGINSHEETB
	
}
